import { Navbar } from "@/components/navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={` antialiased`}>
        <Navbar />
        <main className="max-w-screen-lg mx-auto">{children}</main>
      </body>
    </html>
  );
}
